# Site settings
title: Less is More
email: your-email@domain.com
description: "This is a compilation of my thoughts, ideas that inspire me. Things I care deeply about. I try to articulate as much as possible. Please excuse any ineloquency."
baseurl: ""
url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
