# Site settings
title: Less is More
email: your-email@domain.com
description: "Few Thoughts & Ideas about Web Development"
baseurl: ""
url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
