# Site settings
title: Less is More
email: geetavin464@gmail.com
description: "Blog of a minimalist. I prefer simplicity to complexity."
baseurl: ""
url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
