# Site settings
title: Less is More
email: your-email@domain.com
description: "Minimalist Thoughts, Ideas and Things tend to be most profound"
baseurl: ""
url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
